=== adambartkowiak/towerdefence/public_html/jsonschema/app/model/EntityModel.json
{
  "id": "http://supertowerdefence.pl/jsonschema/app/model/EntityModel.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Entity",
  "description": "Entity",
  "type": "object",
  "properties": {
    "_modelName": {
      "type" : "string"
    },
    "_id": {
      "type": "integer"
    },
    "_team": {
      "type": "integer"
    },
    "_circle": {
      "$ref": "http://supertowerdefence.pl/jsonschema/support/geom/Circle.json"
    },
    "_lastPosition": {
      "$ref": "http://supertowerdefence.pl/jsonschema/support/geom/Point2d.json"
    },
    "_currentStateId": {
      "type": "string"
    },
    "_entityStateListModel": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/EntityStateListModel.json"
    },
    "_currentHp": {
      "type": "number"
    },
    "_angle": {
      "type": "number"
    },
    "_attackCooldown": {
      "type": "number"
    },
    "_buildTime": {
      "type": "number"
    },
    "_currentBuildTime": {
      "type": "number"
    },
    "_selected": {
      "type": "boolean"
    },
    "_selectable": {
      "type": "boolean"
    },
    "_targetable": {
      "type": "boolean"
    },
    "_gatherTime": {
      "type": "number"
    },
    "_resourceStorageArray": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "_resource": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/ResourceModel.json"
    },
    "_carriedResource": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/ResourceModel.json"
    },
    "_moveList": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/TaskListModel.json"
    },
    "_buildList": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/EntityListModel.json"
    },
    "_task": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/TaskModel.json"
    }
  },
  "required": ["_modelName"],
  "additionalProperties": false
}

=== adambartkowiak/towerdefence/public_html/assets/editor/units/team1/barracks_team0.json
{
  "_modelName": "barrack_team0",
  "_team": 0,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 1000,
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 35,
        "_collisionRadius": 35,
        "_groundSpeed": 0,
        "_hp": 1000,
        "_graphicUrl": "assets/graphics/images/barracks_team01.png",
        "_graphicOffset": {
          "_x": -2,
          "_y": 18
        },
        "_rotateGraphicOnMove": false,
        "_availableActionsMenu" : [
          {
            "text": "Warrior",
            "icon": "assets/graphics/icons/warrior_01_icon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 301,
              "3": "warrior_team0"
            }
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          }
        ]
      }
    ]
  }
}

=== adambartkowiak/towerdefence/public_html/assets/editor/units/team1/castle_t01.json
{
  "_modelName": "castle_t01",
  "_team": 1,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 1000,
  "_resourceStorageArray": ["gold", "wood"],
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 43,
        "_viewRadius": 300,
        "_collisionRadius": 43,
        "_groundSpeed": 0,
        "_hp": 1000,
        "_graphicUrl": "assets/graphics/images/castle_t01.png",
        "_graphicOffset": {
          "_x": -6,
          "_y": 35
        },
        "_rotateGraphicOnMove": false,
        "_availableActionsMenu" : [
          {
            "text": "Worker",
            "icon": "assets/graphics/icons/worker_01_icon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 301,
              "3": "worker_t01"
            }
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          }
        ]
      }
    ]
  }
}

=== adambartkowiak/towerdefence/public_html/assets/editor/units/team1/tower_t01.json
{
  "_modelName": "tower_t01",
  "_team": 1,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 1000,
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 23,
        "_collisionRadius": 23,
        "_viewRadius": 600,
        "_selectTargetRadius": 250,
        "_groundSpeed": 0,
        "_hp": 1000,
        "_graphicUrl": "assets/graphics/images/tower_t01.png",
        "_graphicOffset": {
          "_x": -4,
          "_y": 35
        },
        "_rotateGraphicOnMove": false
      },
      {
        "_id": "inconstrucion",
        "_mass": -1,
        "_radius": 23,
        "_collisionRadius": 23,
        "_groundSpeed": 0,
        "_hp": 1000,
        "_graphicUrl": "assets/graphics/images/tower_t01.png",
        "_graphicOffset": {
          "_x": -4,
          "_y": 35
        },
        "_rotateGraphicOnMove": false
      }
    ]
  }
}

=== adambartkowiak/towerdefence/public_html/assets/editor/units/team1/cottage01_t01.json
{
  "_modelName": "cottage01_t01",
  "_team": 1,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 1000,
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 25,
        "_viewRadius": 200,
        "_collisionRadius": 25,
        "_groundSpeed": 0,
        "_hp": 1000,
        "_graphicUrl": "assets/graphics/images/cottage01_t01.png",
        "_graphicOffset": {
          "_x": 0,
          "_y": 18
        },
        "_rotateGraphicOnMove": false
      }
    ]
  }
}

=== adambartkowiak/towerdefence/public_html/assets/editor/objects/rock02.json
{
  "_modelName": "rock02",
  "_team": 0,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 100,
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 30,
        "_collisionRadius": 25,
        "_groundSpeed": 0,
        "_hp": 100,
        "_graphicUrl": "assets/graphics/images/rock02.png",
        "_graphicOffset": {
          "_x": 0,
          "_y": 30
        },
        "_rotateGraphicOnMove": false
      }
    ]
  }
}

=== adambartkowiak/towerdefence/public_html/assets/editor/units/team1/barracks01_t01.json
{
  "_modelName": "barracks01_t01",
  "_team": 1,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 1000,
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 35,
        "_viewRadius": 200,
        "_collisionRadius": 35,
        "_groundSpeed": 0,
        "_hp": 1000,
        "_graphicUrl": "assets/graphics/images/barracks01_t01.png",
        "_graphicOffset": {
          "_x": -2,
          "_y": 18
        },
        "_rotateGraphicOnMove": false,
        "_availableActionsMenu" : [
          {
            "text": "Warrior",
            "icon": "assets/graphics/icons/warrior_01_icon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 301,
              "3": "warrior_t01"
            }
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          }
        ]
      }
    ]
  }
}

=== adambartkowiak/towerdefence/public_html/assets/editor/units/team1/castle_team0.json
{
  "_modelName": "castle_team0",
  "_team": 0,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 1000,
  "_resourceStorageArray": ["gold", "wood"],
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 43,
        "_collisionRadius": 43,
        "_groundSpeed": 0,
        "_hp": 1000,
        "_graphicUrl": "assets/graphics/images/castle_01.png",
        "_graphicOffset": {
          "_x": -6,
          "_y": 35
        },
        "_rotateGraphicOnMove": false,
        "_availableActionsMenu" : [
          {
            "text": "Worker",
            "icon": "assets/graphics/icons/worker_01_icon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 301,
              "3": "worker_team0"
            }
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          }
        ]
      }
    ]
  }
}

=== adambartkowiak/towerdefence/public_html/assets/editor/units/team1/worker_team0.json
{
  "_modelName": "worker_team0",
  "_team": 1,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 300,
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": 0,
        "_radius": 10,
        "_collisionRadius": 10,
        "_viewRadius": 200,
        "_selectTargetRadius": 200,
        "_groundSpeed": 80,
        "_hp": 300,
        "_graphicUrl": "assets/graphics/images/worker_01.png",
        "_graphicOffset": {
          "_x": 0,
          "_y": 16
        },
        "_rotateGraphicOnMove": false,
        "_entityAttackListModel": {
          "_elements": [
            {
              "_id": "melee",
              "_minRange": 0,
              "_maxRange": 5,
              "_rate": 1000,
              "_damage": 100,
              "_createBullet": false
            },
            {
              "_id": "range",
              "_minRange": 5,
              "_maxRange": 150,
              "_rate": 500,
              "_createBullet": true,
              "_bulletOffset": {
                "_x": 0,
                "_y": 18
              },
              "_bulletEntity": {
                "_modelName": "bullet_01",
                "_currentStateId": "default",
                "_selectable": false,
                "_entityStateListModel": {
                  "_elements": [
                    {
                      "_id": "default",
                      "_mass": 0,
                      "_radius": 5,
                      "_collisionRadius": 5,
                      "_selectTargetRadius": 1000,
                      "_groundSpeed": 500,
                      "_removeAfterHit": true,
                      "_graphicUrl": "assets/graphics/images/bullet0.png",
                      "_graphicOffset": {
                        "_x": 0,
                        "_y": 0
                      },
                      "_entityAttackListModel": {
                        "_elements": [
                          {
                            "_id": "melee",
                            "_minRange": 0,
                            "_maxRange": 5,
                            "_rate": 1,
                            "_damage": 20,
                            "_createBullet": false
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            }
          ]
        },
        "_availableActionsMenu": [
          {
            "text": "MOVE",
            "icon": "assets/graphics/icons/moveicon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 400
            }
          },
          {
            "text": "Cancel",
            "icon": "assets/graphics/icons/cancelicon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 2
            }
          },
          {
            "text": "Hold",
            "icon": "assets/graphics/icons/holdicon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 103
            }
          },
          {
            "text": "Patrol",
            "icon": "assets/graphics/icons/patrolicon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 402
            }
          },
          {
            "text": "Attack",
            "icon": "assets/graphics/icons/attackicon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 401
            }
          },
          {
            "text": "Gather",
            "icon": "assets/graphics/icons/gathericon.png",
            "action": {
              "1": "##GENERATE_GUID##",
              "2": 403
            }
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": "Build",
            "icon": "assets/graphics/icons/castle_01_icon.png",
            "elements": [
              {
                "text": "Castle",
                "icon": "assets/graphics/icons/castle_01_icon.png",
                "action": {
                  "1": "##GENERATE_GUID##",
                  "2": 404,
                  "3": "castle_team0"
                }
              },
              {
                "text": "Barrack",
                "icon": "assets/graphics/icons/tower_01_icon.png",
                "action": {
                  "1": "##GENERATE_GUID##",
                  "2": 404,
                  "3": "barrack_team0"
                }
              },
              {
                "text": "Tower",
                "icon": "assets/graphics/icons/tower_01_icon.png",
                "action": {
                  "1": "##GENERATE_GUID##",
                  "2": 404,
                  "3": "tower_team0"
                }
              },
              {
                "text": null,
                "icon": null,
                "action": null
              },
              {
                "text": null,
                "icon": null,
                "action": null
              },
              {
                "text": null,
                "icon": null,
                "action": null
              },
              {
                "text": null,
                "icon": null,
                "action": null
              },
              {
                "text": null,
                "icon": null,
                "action": null
              },
              {
                "text": null,
                "icon": null,
                "action": null
              },
              {
                "text": null,
                "icon": null,
                "action": null
              },
              {
                "text": null,
                "icon": null,
                "action": null
              },
              {
                "text": "Back",
                "icon": "assets/graphics/icons/backicon.png",
                "action": {
                  "1": "##GENERATE_GUID##",
                  "2": 1005
                }
              }
            ]
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          },
          {
            "text": null,
            "icon": null,
            "action": null
          }
        ]
      },
      {
        "_id": "withgold",
        "_mass": 0,
        "_radius": 12,
        "_collisionRadius": 12,
        "_viewRadius": 150,
        "_selectTargetRadius": 150,
        "_groundSpeed": 50,
        "_graphicUrl": "assets/graphics/images/worker_01withgold.png",
        "_graphicOffset": {
          "_x": 0,
          "_y": 18
        },
        "_rotateGraphicOnMove": false
      },
      {
        "_id": "withwood",
        "_mass": 0,
        "_radius": 12,
        "_collisionRadius": 12,
        "_viewRadius": 150,
        "_selectTargetRadius": 150,
        "_groundSpeed": 50,
        "_graphicUrl": "assets/graphics/images/worker_01withwood.png",
        "_graphicOffset": {
          "_x": 0,
          "_y": 18
        },
        "_rotateGraphicOnMove": false
      }
    ]
  }
}
