=== adambartkowiak/towerdefence/public_html/jsonschema/app/model/EntityModel.json
{
  "id": "http://supertowerdefence.pl/jsonschema/app/model/EntityModel.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Entity",
  "description": "Entity",
  "type": "object",
  "properties": {
    "_modelName": {
      "type" : "string"
    },
    "_id": {
      "type": "integer"
    },
    "_team": {
      "type": "integer"
    },
    "_circle": {
      "$ref": "http://supertowerdefence.pl/jsonschema/support/geom/Circle.json"
    },
    "_lastPosition": {
      "$ref": "http://supertowerdefence.pl/jsonschema/support/geom/Point2d.json"
    },
    "_currentStateId": {
      "type": "string"
    },
    "_entityStateListModel": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/EntityStateListModel.json"
    },
    "_currentHp": {
      "type": "number"
    },
    "_angle": {
      "type": "number"
    },
    "_attackCooldown": {
      "type": "number"
    },
    "_buildTime": {
      "type": "number"
    },
    "_currentBuildTime": {
      "type": "number"
    },
    "_selected": {
      "type": "boolean"
    },
    "_selectable": {
      "type": "boolean"
    },
    "_targetable": {
      "type": "boolean"
    },
    "_gatherTime": {
      "type": "number"
    },
    "_resourceStorageArray": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "_resource": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/ResourceModel.json"
    },
    "_carriedResource": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/ResourceModel.json"
    },
    "_moveList": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/TaskListModel.json"
    },
    "_buildList": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/EntityListModel.json"
    },
    "_task": {
      "$ref": "http://supertowerdefence.pl/jsonschema/app/model/TaskModel.json"
    }
  },
  "required": ["_modelName"],
  "additionalProperties": false
}

=== adambartkowiak/towerdefence/public_html/assets/editor/objects/bush02.json
{
  "_modelName": "bush02",
  "_team": 0,
  "_selectable": true,
  "_targetable": true,
  "_currentHp": 100,
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 20,
        "_collisionRadius": 20,
        "_groundSpeed": 0,
        "_hp": 100,
        "_graphicUrl": "assets/graphics/images/bush02.png",
        "_graphicOffset": {
          "_x": 0,
          "_y": 20
        },
        "_rotateGraphicOnMove": false
      }
    ]
  }
}

=== adambartkowiak/towerdefence/public_html/assets/editor/objects/tree01.json
{
  "_modelName": "tree01",
  "_team": 0,
  "_selectable": true,
  "_targetable": true,
  "_resource": {
    "_name": "wood",
    "_value": 100,
    "_maxValue": 100
  },
  "_currentHp": 100,
  "_currentStateId": "default",
  "_entityStateListModel": {
    "_elements": [
      {
        "_id": "default",
        "_mass": -1,
        "_radius": 10,
        "_collisionRadius": 10,
        "_groundSpeed": 0,
        "_hp": 100,
        "_graphicUrl": "assets/graphics/images/tree01.png",
        "_graphicOffset": {
          "_x": 0,
          "_y": 18
        },
        "_rotateGraphicOnMove": false
      },
      {
        "_id": "noresources",
        "_mass": -1,
        "_radius": 10,
        "_collisionRadius": 0,
        "_groundSpeed": 0,
        "_graphicUrl": "assets/graphics/images/tree01cut.png",
        "_graphicOffset": {
          "_x": 0,
          "_y": 18
        },
        "_rotateGraphicOnMove": false
      }
    ]
  }
}
